### ISSUE TITLE
E-0003: License limit reached

### ISSUE THREAD

**Issue by himanshu2416** [Trivadis/plsql-cop-sonar#3]
I am getting this issue in one of the large files in our repository. is there any solution to scan such file.
we are using the jar 
sonar-plsql-cop-standalone-8.9.0.jar 
for sonar 8.9

**Comment by rolandstirnimann** [comment]
Hi Himanshu, thanks for your interest in our product db* CODECOP. All license limits will be gone if you buy a commercial license (see here: https://cdn.trivadis.com/downloads/dbCODECOP-fs-en.pdf).
So, the answer is yes, you can scan large files with the commerical version of db* CODECOP.

Please get in contact with me (dbstar@trivadis.com) if I can assist you with an official quote.

Regards
Roland

**Comment by PhilippSalvisberg** [comment]
@himanshu2416 Alternatively, you can use the [SQL Developer Extension](https://github.com/Trivadis/plsql-cop-sqldev) to analyze the large file. The tool is free and there are no license limits. However, SonarQube is much better suited to analyze a large code base. If you are looking for a free solution, then I suggest to have a look at [ZPA](https://felipezorzo.com.br/zpa/). But if you ask me I'd suggest to license db* CODECOP. It's worth every penny. 🤓

**Comment by himanshu2416** [comment]
> So, the answer is yes, you can scan large files with the commerical version of db* CODECOP.
@rolandstirnimann Just need to know how many line of code per file is allowed in the free version. This will help us analyse how many of our files will need the lincensed scan.

**Comment by himanshu2416** [comment]
@rolandstirnimann  Is there any way to deactivate the rule for E-0003: License limit reached?

**Comment by rolandstirnimann** [comment]
@himanshu2416 The trial version has a maximum of 5000 lines.

**Comment by himanshu2416** [comment]
@rolandstirnimann Thank you for the valuable support.
 @PhilippSalvisberg Thank you for the suggestion i will definitely use the extension

**Comment by PhilippSalvisberg** [comment]
@himanshu2416, your welcome. 

I closed the issue since I consider it resolved.

**Comment by zrh535** [comment]
@PhilippSalvisberg after the Accenture acquisition, how can we obtain a license? I'm struggling to find anything under the Accenture website.

**Comment by PhilippSalvisberg** [comment]
Please contact @rolandstirnimann directly via e-mail at roland.stirnimann@accenture.com. He can provide you the necessary information. Thank you.
