### ISSUE TITLE
No of files limit in a scan

### ISSUE THREAD

**Issue by himanshu2416** [Trivadis/plsql-cop-sonar#4]
Is there a limit for the number of files scanned in one go?

**Comment by PhilippSalvisberg** [comment]
With a commercial license there is no limit. The included preview/trial license has the following limitations:

- Number of files: unlimited
- Number of Lines: 5000
- Number of Commands: 2000
- Number of Bytes: 400000
- Valid thru: 2022-04-01 (current value for v8.9.2)

After reaching one of the limitations the analysis stops with an E-0003 error (License limit reached).

**Comment by PhilippSalvisberg** [comment]
Closed due to inactivity.
