### ISSUE TITLE
Does Secondary Plugin work in free trial?

### ISSUE THREAD

**Issue by zrh535** [Trivadis/plsql-cop-sonar#6]
Hello,

I configured ZPA + db*CODECOP Secondary Plugin as outlined [here](https://github.com/Trivadis/plsql-cop-sonar#secondary-plugin).  I see a combined total of 178 rules, which seems reasonable to me given the potential for overlapping rules.

However, when I run the scan on a subset of my project, I have far fewer issues detected than when i used db*CODECOP Standalone Plugin.  It looks to me like the 2 rule sets are detected and merged under the Rules tab, but only the base ZPA rules are actually analyzed.

**Comment by PhilippSalvisberg** [comment]
Are the db* CODECOP rules activated for the quality profile of your project? - Can you share the scanner output?

**Comment by zrh535** [comment]
Problem Solved. After creating the extended quality profile, I forgot to activate the db*CODECOP rules so both sets were live.  User Error.
